name: 'install Docker Workflow'
on:    
  pull_request:
  types: [closed]
env:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: First
          run: echo '1'
        - name: Second
          run: echo 'SECOND'
        - name: Third
          run: echo '3'
  build:
    runs-on: ubuntu-lates
    needs: [test]
    - name: Get Repository
      uses: actions/checkout@v3
    - name: Setup Docker qemu
      uses: docker.setup-qemu-action@v1
    - name: Setup Docker buildX
      uses: docker/setup-buildx-action@v1
    - name: echo github
      run: echo '${{toJSON(github)}}'
    - name: login Dockerhub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & Push docker
      uses: docker/build-push-action@v2
      with:
        push: true
        tag: ${{ secrets.DOCKER_USERNAME }}/wether:latest
