name: PR Validator

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: gitActions
    - run: |
        date > generated.txt
        git branch
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm test