name: PR Validator

on:
  #pull_request:
  #  types: [opened, reopened, synchronize]
  push:
    branches-ignore:
      - master
    paths-ignore:
      - 'assets/*'
jobs:
  build:
    if: github.actor == 'VilakshanDadwal'
    runs-on: ubuntu-latest

    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm test

    - name: Create bundle
      run: npm run build

    - name: Copy bundle to assets and commit
      run: |
        git config user.name ABCD
        git config user.email ABCD@github.com
        git add assets
        git commit -m "Updating assets"
        git push
