name: Asset Updated

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'assets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Unit test status check not needed for uploading assets"

