name: PR Validator

on:
  push:
    paths-ignore:
      - 'assets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{github.head_ref}}
        token: ${{ secrets.PAT }}
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm test

    - name: Create bundle
      run: npm run build

    - name: Copy bundle to assets and commit
      run: |
        git config user.name ABCD
        git config user.email ABCD@github.com
        git add assets
        git commit -m "Updating assets"
        git push
