# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Gamedev

env:
  DAY_OF_WEEK: Monday
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn set version 1.22.19
      - name: Get artifacts
        run: yarn
      - run: yarn test
      - run: echo "my test step"
      - run: echo "my2 test step"
  bump:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@v10.0.1'
        with:
          tag-prefix: 'v'
          target-branch: 'master'
          commit-message: '${{env.DAY_OF_WEEK}} bumps version'

