# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Gamedev

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn set version $(cat package.json | grep yarn@ | cut -d@ -f2 | cut -d "\"" -f 1)
      - run: yarn
      - run: yarn test
      - run: echo "my test step"
      - run: printenv
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@v10.0.1'
        with:
          tag-prefix: 'v'
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          from-tag: v1.0
          to-tag: HEAD