name: Tag and Bundle

on:
  push:
    branches:
      - master
jobs:

  bundle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install

    - name: Create bundle
      run: npm run build

    - name: Copy bundle to assets and commit
      id: bundle
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add assets
        git diff --staged --quiet || (git commit -m "Updating assets" && git push origin)
