name: Bundle and Release

on:
  push:
    branches:
      - master
    paths-ignore:
    - 'assets/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install

    - name: Create bundle
      run: npm run build

    - name: Copy bundle to assets and commit
      run: |
        git checkout -b Bundle_PR
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add assets
        git commit -m "Updating assets"
        git push origin Bundle_PR

    - name: Create Pull Request for bundle
      run: gh pr create --base main --head Bundle_PR --title "Updated bundle PR" --body "Created bundle"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}