name: Bundle and Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install

    - name: Create bundle
      run: npm run build

    - name: Find package version
      id: packageVersion
      uses: sergeysova/jq-action@v2
      with:
        cmd: 'jq .version package.json -r'

    - name: Create Release
      run: gh release create -d ${{ steps.packageVersion.outputs.value }} ./dist/*.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

