name: Bundle and Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install

    - name: Create bundle
      run: npm run build

    - name: Find package version
      id: packageVersion
      run: |
        packageJson=`cat package.json`
        #packageJson="${packageJson//'%'/'%25'}"
        #packageJson="${packageJson//$'\n'/'%0A'}"
        #packageJson="${packageJson//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "package_json=$packageJson" >> $GITHUB_OUTPUT

    - name: Print version
      run: echo "Package Json is ${{steps.packageVersion.outputs.package_json}}"

    - name: Create Release
      run: gh release create -d "v${{ fromJson(steps.packageVersion.outputs.package_json).version }}" ./dist/*.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

