name: Tag the main branch

on:
  push:
    branches:
      - master
    paths:
      - 'assets/**'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Find package version
      id: packageVersion
      run: echo "package_json=$(cat package.json | tr -d "\n")" >> $GITHUB_OUTPUT

    - name: Print version
      run: echo "Package Json is ${{steps.packageVersion.outputs.package_json}}"

    - name: Tag main branch
      run: |
        package_version=${{ fromJson(steps.packageVersion.outputs.package_json).version }}
        git tag "v${package_version}"
        git push origin "v${package_version}"