name: Package Version Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get package json of current branch
      id: branchPackageJson
      run: |
        echo "branchPackageJson=$(cat package.json | tr -d "\n") >> $GITHUB_OUTPUT

    - uses: actions/checkout@v3
      with:
        ref: master

    - name: Get package json of main
      id: mainPackageJson
      run: |
        echo "mainPackageJson=$(cat package.json | tr -d "\n") >> $GITHUB_OUTPUT

    - name: Compare versions
      if: ${{ fromJson(steps.mainPackageJson.outputs.branchPackageJson).version }} == ${{ fromJson(steps.branchPackageJson.outputs.mainPackageJson).version }}
      run: exit 1